justice_league = ["Superman", "Batman", "Wonder Woman", 
                  "Flash", "Aquaman", "Green Lantern"]
print("1. Number of members:", len(justice_league))
print("Current List:", justice_league)
print()
justice_league.append("Batgirl")
justice_league.append("Nightwing")
print("2. After adding Batgirl and Nightwing:")
print(justice_league)
print()
justice_league.remove("Wonder Woman")
justice_league.insert(0, "Wonder Woman")
print("3. After moving Wonder Woman to the beginning:")
print(justice_league)
print()
justice_league.remove("Superman")
aquaman_index = justice_league.index("Aquaman")
justice_league.insert(aquaman_index + 1, "Superman")
print("4. After separating Aquaman and Flash:")
print(justice_league)
print()
justice_league = ["Cyborg", "Shazam", "Hawkgirl", 
                  "Martian Manhunter", "Green Arrow"]
print("5. After replacing with new team:")
print(justice_league)
print()
justice_league.sort()
print("6. After sorting alphabetically:")
print(justice_league)
print()
print("BONUS: The new leader is:", justice_league[0])